[package]
name = "pulse"
version = "0.1.0"
edition = "2024"

[dependencies]
pulse_core = { workspace = true }
pulse_core_macros = { workspace = true }
crossterm = { workspace = true }
ratatui = { workspace = true }
tokio = { version = "1.0", features = ["full"] }
